CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(40) NOT NULL,
  "email" varchar(70) NOT NULL,
  "password" numeric NOT NULL,
  "fecha_nac" date NOT NULL
);

CREATE TABLE "curses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "descrption" varchar(100) NOT NULL,
  "fk_level" int NOT NULL,
  "fk_categorias" int NOT NULL,
  "fk_course_video" int NOT NULL,
  "fk_teacher" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(100) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "user_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_users" int NOT NULL,
  "fk_curses" int NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "roles_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_users" int NOT NULL,
  "fk_roles" int NOT NULL
);

ALTER TABLE "user_courses" ADD FOREIGN KEY ("fk_users") REFERENCES "users" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("fk_curses") REFERENCES "curses" ("id");

ALTER TABLE "curses" ADD FOREIGN KEY ("fk_course_video") REFERENCES "course_video" ("id");

ALTER TABLE "curses" ADD FOREIGN KEY ("fk_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "curses" ADD FOREIGN KEY ("fk_categorias") REFERENCES "categories" ("id");

ALTER TABLE "curses" ADD FOREIGN KEY ("fk_level") REFERENCES "level" ("id");

ALTER TABLE "roles_users" ADD FOREIGN KEY ("fk_users") REFERENCES "users" ("id");

ALTER TABLE "roles_users" ADD FOREIGN KEY ("fk_roles") REFERENCES "roles" ("id");

INSERT INTO level (name) VALUES ('principiantes');
INSERT INTO level (name) VALUES ('medios');
INSERT INTO level (name) VALUES ('avanzados');


INSERT INTO categories (name) VALUES ('Javascript');
INSERT INTO categories (name) VALUES ('NodeJs');


INSERT INTO course_video (title, url) VALUES ('javaScript modulo 1', 'https://www.youtube.com/watch?v=RqQ1d1qEWlE');
INSERT INTO course_video (title, url) VALUES ('NodeJs modulo 1', 'https://www.youtube.com/watch?v=BhvLIzVL8_o');

INSERT INTO teacher (name) VALUES ('Brenda');
INSERT INTO teacher (name) VALUES ('Ian Rosas');

INSERT INTO roles (name) VALUES ('Estudiante');
INSERT INTO roles (name) VALUES ('Profesor');
INSERT INTO roles (name) VALUES ('Admin');

INSERT INTO users (name, email, password, fecha_nac) VALUES ('Jose', 'jotik1989@gmail.com', '1234', '29/12/1989');
INSERT INTO users (name, email, password, fecha_nac) VALUES ('Andres', 'andres_varela@gmail.com', '2023', '20/01/1925');

INSERT INTO roles_users (fk_users, fk_roles) VALUES (1, 1);
INSERT INTO roles_users (fk_users, fk_roles) VALUES (2, 3);


INSERT INTO curses (title, descrption, fk_level, fk_categorias, fk_course_video, fk_teacher) VALUES ('JavaScript para principiantes', 'Iniciación del lenguaje Javascript para principiantes volumen1', 1, 1, 1, 1);
INSERT INTO curses (title, descrption, fk_level, fk_categorias, fk_course_video, fk_teacher) VALUES ('NodeJs para principiantes', 'Iniciación del lenguaje NodeJs para principiantes volumen1', 1, 2, 2, 2);

INSERT INTO user_courses (fk_users, fk_curses) VALUES (1, 1);
INSERT INTO user_courses (fk_users, fk_curses) VALUES (2, 2);
INSERT INTO user_courses (fk_users, fk_curses) VALUES (2, 1);






















